language: python
python:
- 2.7
install:
- pip install -r requirements.txt
- pip install .
- pip install -e git+https://github.com/napalm-automation/napalm-base.git@develop#egg=napalm-base
deploy:
  provider: pypi
  user: dbarroso
    # !!passwd needed
  password:
  on:
    tags: true
    branch: master
script:

- cd test/unit
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_bgp_config
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_bgp_neighbors
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_bgp_neighbors_detail
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_environment
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_facts
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_interfaces
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_interfaces_counters
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_lldp_neighbors
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_lldp_neighbors_detail
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_arp_table
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_ntp_peers
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_ntp_stats
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_ntp_servers
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_interfaces_ip
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_mac_address_table
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_route_to
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_snmp_information
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_users
- nosetests -v TestIOSXRRPCDriver:TestGetterIOSXRRPCDriver.test_get_optics
- cd ../..
